Description: >
  Useful SSM run documents

Resources:

  InstallDockstoreDeploySSMDocument:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: Command
      Name: Clone-Dockstore-Deploy
      Content:
        schemaVersion: "2.2"
        description: "Installs SSH keys needed to access dockstore/dockstore-deploy, and clones the repo in /home/ubuntu/dockstore-deploy"
        mainSteps:
          - action: "aws:runShellScript"
            name: "createuser"
            inputs:
              runCommand:
                - export DEBIAN_FRONTEND=noninteractive sudo apt-get -y update && sudo apt-get -y install jq
                - sudo mkdir -p /home/ubuntu/.ssh
                - sudo aws ssm get-parameter --name "/DeploymentConfig/DockstoreDeployPublicKey" | jq -r .Parameter.Value > /home/ubuntu/.ssh/id_rsa_dockstore_deploy.pub
                - sudo aws ssm get-parameter --name "/DeploymentConfig/DockstoreDeployPrivateKey" | jq -r .Parameter.Value > /home/ubuntu/.ssh/id_rsa_dockstore_deploy
                - sudo chmod 644 /home/ubuntu/.ssh/id_rsa_dockstore_deploy.pub
                - sudo chmod 600 /home/ubuntu/.ssh/id_rsa_dockstore_deploy
                - sudo chown ubuntu:ubuntu /home/ubuntu/.ssh/id_rsa_dockstore_deploy{,.pub}
                - GIT_SSH_COMMAND='ssh -i /home/ubuntu/.ssh/id_rsa_dockstore_deploy -o IdentitiesOnly=yes' git clone git@github.com:chmreid/dockstore-deploy.git /home/ubuntu/dockstore-deploy
