Description: >
  Useful SSM run documents

Resources:

  CloneDockstoreDeploySSMDocument:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: Command
      Name: Clone-Dockstore-Deploy
      Content:
        schemaVersion: "2.2"
        description: "Installs SSH keys needed to access dockstore/dockstore-deploy, and clones the repo in /home/ubuntu/dockstore-deploy"
        mainSteps:
          - action: "aws:runShellScript"
            name: "createuser"
            inputs:
              runCommand:
                - DEBIAN_FRONTEND=noninteractive sudo apt-get -y update
                - sudo apt-get -y install jq
                - sudo mkdir -p /home/ubuntu/.ssh && echo "SSH dir now exists"
                - sudo aws ssm get-parameter --name "/DeploymentConfig/DockstoreDeployPublicKey" | jq -r .Parameter.Value > /home/ubuntu/.ssh/id_rsa_dockstore_deploy.pub
                - test -e /home/ubuntu/.ssh/id_rsa_dockstore_deploy.pub && echo "Successfully got public key from SSM" || echo "Error getting public key from AWS"
                - sudo aws ssm get-parameter --name "/DeploymentConfig/DockstoreDeployPrivateKey" | jq -r .Parameter.Value > /home/ubuntu/.ssh/id_rsa_dockstore_deploy
                - test -e /home/ubuntu/.ssh/id_rsa_dockstore_deploy && echo "Successfully got private key from SSM" || echo "Error getting private key from AWS"
                - sudo chmod 644 /home/ubuntu/.ssh/id_rsa_dockstore_deploy.pub && echo "Successfully chmodded public key"
                - sudo chmod 600 /home/ubuntu/.ssh/id_rsa_dockstore_deploy && echo "Successfully chmodded private key"
                - sudo chown ubuntu:ubuntu /home/ubuntu/.ssh/id_rsa_dockstore_deploy && echo "Successfully chowned public key"
                - sudo chown ubuntu:ubuntu /home/ubuntu/.ssh/id_rsa_dockstore_deploy.pub && echo "Successfully chowned private key"
                - sudo rm -fr /home/ubuntu/dockstore-deploy
                - GIT_SSH_COMMAND='ssh -i /home/ubuntu/.ssh/id_rsa_dockstore_deploy -o IdentitiesOnly=yes -o StrictHostKeyChecking=no' git clone git@github.com:chmreid/dockstore-deploy.git /home/ubuntu/dockstore-deploy

  FalcoAgentRestartSSMCommandDoc:
    Type: AWS::SSM::Document
    Properties:
      Content:
        schemaVersion: "2.2"
        description: "Reload the Falco configuration and restart the Falco engine without killing the PID."
        mainSteps:
        - action: "aws:runShellScript"
          name: "reloadfalco"
          inputs:
            runCommand:
              - "kill -1 $(cat /var/run/falco.pid)"
      DocumentType: Command
      Name: Falco-Agent-Restart

